### ISSUE TITLE
Dataset availability? 

### ISSUE THREAD

**Issue by innat** [nayeemmz/TeliNet#1]
@nayeemmz, Hello Dr. Teli, thanks for your wonderful work, [TeliNet](https://arxiv.org/abs/2107.04930), and for open-sourcing it. 

I like to run the code but unfortunately couldn't find the used dataset, MIA-COV19D. Could you please inform me whether it's publicly available to download or restricted by some rules? Thank you.

**Comment by nayeemmz** [comment]
Hi Mohammed,

Thanks for reaching out.
It was part of the ICCV 2021, https://mlearn.lincoln.ac.uk/mia-cov19d/
The data set is owned by Dimitrios Kollias, ***@***.***

You may want to reach out to him for the data set. It takes him a few days
to respond. If nothing comes out of contacting him by June 9th, please let
me know and I will try to do something.

Best,
Mohammad

**Comment by innat** [comment]
@nayeemmz hello, sorry for the dealy response. I missed your reply in time. 
I've contacted Dr. Dimitrios Kollias and used [`D.Kollias@greenwich.ac.uk`](https://arxiv.org/pdf/2106.07524.pdf) this email to reach. I will update you in 2 days.

**Comment by innat** [comment]
@nayeemmz 
I sent mail on 9 June to Dr. Dimitrios Kollias regarding the dataset but unfortunately didn't hear back.  Could you please take a look into this? Thank you.
